
title: Geo Imagine Developer
email: thomas.gumbricht@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Remote sensing and spatial data developer guide
  for global natural resources mapping,
  inventories and monitoring.
baseurl: "/setup-blog" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  karttur
rouge: true
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
